---
kind: pipeline
type: docker
name: Verify

platform:
  os: linux
  arch: amd64

environment:
  NGINX_VERSION: 1.24.0
  NGINX_MODULES_DIR: /opt/nginx-modules
  HEADERS_MORE_VERSION: 'v0.35'

steps:
  - name: Compile nginx
    image: ubuntu/nginx:1.24-23.10_beta
    commands:
      - apt update
      - apt install wget -y
      - mkdir -p /opt/nginx-modules
      - wget "https://github.com/openresty/headers-more-nginx-module/archive/refs/tags/$${HEADERS_MORE_VERSION}.tar.gz"
      - tar -xvzf $${HEADERS_MORE_VERSION}.tar.gz
      - mv headers-more-nginx-module-* $${NGINX_MODULES_DIR}/headers-more-nginx-module
      - mkdir -p /opt/nginx
      - wget "http://nginx.org/download/nginx-$${NGINX_VERSION}.tar.gz"
      - tar -xvzf nginx-$${NGINX_VERSION}.tar.gz
      - cd nginx-$${NGINX_VERSION}
      - ./configure --prefix=/opt/nginx --add-dynamic-module=$${NGINX_MODULES_DIR}/headers-more-nginx-module  --with-compat
      - cd nginx-$${NGINX_VERSION}
      - make
      - make install

  - name: Verify nginx confiy
    image: nginx:$${NGINX_VERSION}-bookworm
    commands:
      - nginx -p /opt/nginx -t

---
kind: signature
hmac: 889f2181f1c89b0906b3a95b4fe08fb6a9e91faaf02059c4fe264dac06ce9c1d

...
