---
kind: pipeline
type: docker
name: Verify

platform:
  os: linux
  arch: amd64

environment:
  NGINX_VERSION: 1.24.0
  NGINX_MODULES_DIR: /opt/nginx-modules
  HEADERS_MORE_VERSION: 'v0.35'

steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive

  - name: Verify nginx config
    image: ubuntu/nginx:1.24-23.10_beta
    commands:
      - nginx -t

  - name: Compile nginx
    image: ubuntu/nginx:1.24-23.10_beta
    commands:
      - NGINX_CONFIG_PATH=$(pwd)
      - apt update
      - apt install -y
        wget
        build-essential
        libpcre3
        libpcre3-dev
        zlib1g
        zlib1g-dev
        libssl-dev
        tree
      - wget "http://nginx.org/download/nginx-$${NGINX_VERSION}.tar.gz"
      - tar -xvzf nginx-$${NGINX_VERSION}.tar.gz
      - cd nginx-$${NGINX_VERSION}
      - ./configure --prefix=/opt/nginx
        --add-dynamic-module=../modules-available/headers-more-nginx-module
        --with-compat
      - make
      - make install
      - tree /opt/nginx

---
kind: signature
hmac: 889f2181f1c89b0906b3a95b4fe08fb6a9e91faaf02059c4fe264dac06ce9c1d

...
