---
kind: pipeline
type: docker
name: Verify

platform:
  os: linux
  arch: amd64

steps:
  - name: Verify nginx confiy
    image: nginx:1.25-bookworm
    commands:
      - nginx -t

---
kind: signature
hmac: f0a4a11afdeeb438700c0abb4a1a3f11c368b6b586cd53ab5735fd5ed4f43224

...
